export const roomRegistry = [
  {
    id: "hall-of-arrival",
    zoneId: "arrival",
    label: "Hall of Arrival",
    title: "Hall of Arrival",
    caption: "A calibration chamber for breath, gaze, and first attunement.",
    sceneFamily: "signal-object",
    artworkSrc: "/consciousness/artworks/hall-of-arrival.svg",
    z: 1.2,
  },
  {
    id: "signal-corridor",
    zoneId: "signal-corridor",
    label: "Signal Corridor",
    title: "Signal Corridor",
    caption: "A threshold corridor where rhythm, pulse, and spatial drift begin.",
    sceneFamily: "cloth",
    artworkSrc: "/consciousness/artworks/signal-corridor.svg",
    z: -6.2,
  },
  {
    id: "membrane-chamber",
    zoneId: "membrane-chamber",
    label: "Membrane Chamber",
    title: "Membrane Chamber",
    caption: "A living membrane field that suggests future voice and touch response.",
    sceneFamily: "membrane",
    artworkSrc: "/consciousness/artworks/membrane-chamber.svg",
    z: -13.6,
  },
  {
    id: "portal-atrium",
    zoneId: "portal-atrium",
    label: "Portal Atrium",
    title: "Portal Atrium",
    caption: "A proto-portal chamber for future crossings, state shifts, and world mutation.",
    sceneFamily: "portal-surface",
    artworkSrc: "/consciousness/artworks/portal-atrium.svg",
    z: -21.4,
  },
];
